plugins:
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - typescript:
version: 2
checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 150
exclude_patterns:
- tests/**/*
- examples/**/*
- dist/**/*
- node_modules/**/*
- coverage/**/*
- src/spec/spec.ts
