engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - typescript:
ratings:
  paths:
  - src/**/*
exclude_paths:
- tests/**/*
- examples/**/*
- dist/**/*
- node_modules/**/*
- coverage/**/*
