env:
  global:
  - CC_TEST_REPORTER_ID=8998d7a6188fbac1cf8fadb5c654a4cf1f23e96c5b9ba489d195861a310d1282
language: node_js'
cache:
  yarn: true
node_js:
- node
- '8'
sudo: false
install:
- yarn
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- yarn lint
- yarn build
- yarn coverage --runInBand
- yarn coveralls
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  skip_cleanup: true
  provider: npm
  email: arminhammer@gmail.com
  api_key:
    secure: gHpcTK5bO/FJSiymWRkrD714/hFP/hCcT0abHgADRb6bhFskHqCgfWgPkLR1sITWykAE1b1JxL3J/YtUcxhW7RaeQOH887Bwv8YJxDnefytFxZVkwcIl6cMLTL0lPcCBweW/2GYNNNRjRta1DKA73KaPgLzpTfhot/vFoGuXAWcTiIUgqsbpf23mquyA+3PmXqED2Iq6mwC6bg8ZXbfKWzVd3AOpLte0CN7vqRMoYQWCt65UUns2YQaX97ScH87ufjqBXMJnx2NEh/uuOtddXXXAJUrP50lI5/we6PjpV9XjJcQ6cWawncf7PwB7ATd1OkIzHO64WeEvL0uP6SX/m7RuoxM0qN08EiZ8B8tzgXn13GYr60azZomTMXTkikSX0142AHGBR2PGHOoF5wkN59BHZCUwJf5HQDojpzviJO9nXfbX5B24jJK2A9YXfyM766o+l33i1+JyvWM7T9oai7e/C6xt066TIp+rbut26upVNBUzIQwPDaga15L1DZ6CIjVx0eoe1X1rcEa4yGhPogipD0FMbSW40HW3RsFnboQcd7owPtX7cvhnjNq2CLWmJsGuakR7HGMh2HTFiy+UCg14Sxi+KCeHuqz29oGEdBoLCwGpvZphMuuxrbcLkAUTtgLXk2FqGoyJcpowLYeIwJvcT+pGBSHMwrltnc2XozA=
  on:
    branch: master
    repo: arminhammer/wolkenkratzer
